### ISSUE TITLE
Use Relative Path for Image src

### ISSUE THREAD

**Issue by haelmj** [grantrn/portfolio#1]
## Problem
Image is being stored outside repository and absolute paths are currently being used for the image path on line 16. This means that when deployed, the website will fail to load the image as the image does not exist in the deployment environment and the absolute path to the image differs with the directory structure in the deployment environment.

*Note*: Absolute paths are paths that specify a file location starting from the root direcotry(e.g. `C:\Users\Roshan\Documents\file.txt`) while Relative paths give the location relative to the current directory (e.g. if your are currently in the Documents directory and the path to a text file stored in a sub-folder named `assets` will be `./assets/file.txt`

## Solution
**Store your media inside your repository and Use a relative path**
- In your repository, create a folder that will be used to store all the media relevant to your website. Let's assume you name it **assets**.
- Move the required image files into this folder. 
- Replace the absolute path with the relative path to the image. 
   - In VS code, in the explorer on the left pane, right-click on the image file and select *Copy Relative Path*.
   - Remove the existing path on Line 16 and paste the one that has just been copied. Ideally it should look something like this: `./assets/IMG-7071.jpg`

https://github.com/grantrn/portfolio/blob/45bc4ec7e5008a245b4324b8e4372793b8c9cd34/index.html#L16

**Comment by grantrn** [comment]
Thank you, I changed it and it's working now.
